name: river_workspace
publish_to: none

environment:
  sdk: ^3.9.3

workspace:
  - packages/bintools
  - packages/riscv
  - packages/river
  - packages/river_adl
  - packages/river_emulator
  - packages/river_hdl

dev_dependencies:
  coverage: ^1.15.0
