name: river_hdl
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  logging: ^1.3.0
  path: ^1.9.1
  riscv: ^1.0.0
  river: ^1.0.0
  rohd: ^0.6.6
  rohd_bridge: ^0.2.0
  rohd_hcl:
    git:
      url: https://github.com/MidstallSoftware/rohd-hcl.git
      ref: integration
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  dartdoc: ^9.0.0
